In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(
    "datasets/weather_data_apr_may.csv"
)
df

          date  temp_max  temp_min  precipitation
0   2026-04-01      33.5      23.9            0.0
1   2026-04-02      33.5      23.6            0.0
2   2026-04-03      34.9      24.4            0.0
3   2026-04-04      34.6      26.0            0.1
4   2026-04-05      33.8      27.0            2.3
..         ...       ...       ...            ...
56  2026-05-27      32.5      23.1            2.5
57  2026-05-28      36.2      26.0            0.3
58  2026-05-29      36.8      27.5            0.0
59  2026-05-30      37.0      28.2            0.0
60  2026-05-31      35.8      28.1            0.5

[61 rows x 4 columns]

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           61 non-null     str
 1   temp_max       61 non-null     float64
 2   temp_min       61 non-null     float64
 3   precipitation  61 non-null     float64
dtypes: float64(3), str(1)
memory usage: 2.0 KB

In [4]:
df.head(10)

         date  temp_max  temp_min  precipitation
0  2026-04-01      33.5      23.9            0.0
1  2026-04-02      33.5      23.6            0.0
2  2026-04-03      34.9      24.4            0.0
3  2026-04-04      34.6      26.0            0.1
4  2026-04-05      33.8      27.0            2.3
5  2026-04-06      34.7      25.0            0.0
6  2026-04-07      34.5      24.6            0.0
7  2026-04-08      35.5      25.2            0.0
8  2026-04-09      36.3      25.9            0.0
9  2026-04-10      36.8      25.6            0.0

In [5]:
df.shape

(61, 4)

In [6]:
df.isnull().sum()

date             0
temp_max         0
temp_min         0
precipitation    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.dtypes

date                 str
temp_max         float64
temp_min         float64
precipitation    float64
dtype: object

In [9]:
df["date"] = pd.to_datetime(
    df["date"]
)

In [10]:
df["avg_temp"] = (
    df["temp_max"]
    +
    df["temp_min"]
) / 2

In [11]:
df.describe()

                      date   temp_max   temp_min  precipitation   avg_temp
count                   61  61.000000  61.000000      61.000000  61.000000
mean   2026-05-01 00:00:00  36.998361  26.775410       0.324590  31.886885
min    2026-04-01 00:00:00  32.500000  23.100000       0.000000  27.800000
25%    2026-04-16 00:00:00  36.200000  25.900000       0.000000  31.000000
50%    2026-05-01 00:00:00  37.100000  27.000000       0.000000  32.100000
75%    2026-05-16 00:00:00  38.200000  27.900000       0.200000  32.900000
max    2026-05-31 00:00:00  40.000000  29.400000       4.100000  34.650000
std                    NaN   1.656552   1.475088       0.757112   1.443459

In [12]:
df = df.sort_values(
    "date"
)

In [13]:
df.to_csv(
    "datasets/weather_data_cleaned.csv",
    index=False,
)